const BOARDS_CONFIG = {
    BOARD_SLUG_MAP: {
        aave: ["aave"],
        ai: [
            "bittensor",
            "fetch-ai",
            "ocean-protocol",
            "singularitynet",
            "chaingpt",
            "arkham",
            "phala-network",
            "oasis",
            "iexec-rlc",
            "render",
            "ai",
        ],
        alchemix: ["alchemix"],
        alpha: [],
        aptos: ["aptos"],
        arbitrum: ["arbitrum", "offchain-labs"],
        avalanche: ["avalanche"],
        bankless: ["bankless"],
        base: ["base", "coinbase"],
        beginner: [],
        bitcoin: ["bitcoin"],
        canto: ["canto"],
        celestia: ["celestia"],
        chiliz: ["chiliz"],
        dfinity: ["dfinity", "internet-computer"],
        eigenlayer: ["eigenlayer"],
        eos: ["eos"],
        ethereumclassic: ["ethereumclassic"],
        ethereum: ["ethereum", "ethereum-research-forum"],
        functionx: ["function-x"],
        gamefi: [
            "gamefi",
            "blockchain-gaming",
            "the-sandbox",
            "decentraland",
            "ronin",
            "immutablex",
        ],
        impossible: ["impossible-finance"],
        injective: ["injective"],
        kyber: ["kyber-network", "kyberswap"],
        linea: ["linea"],
        liquidstaking: [
            "liquid-staking",
            "lido",
            "rocket-pool",
            "frax",
            "eigenlayer",
            "coinbase-wrapped-staked-eth",
            "swell",
            "ankr",
            "ethereum",
            "swell-ethereum",
        ],
        manta: ["manta-network"],
        metis: ["metis", "metisdao"],
        mina: ["mina", "mina-protocol"],
        moonbeam: ["moonbeam"],
        nft: ["nft"],
        oceanprotocol: ["ocean-protocol"],
        optimism: ["optimism"],
        orbs: ["orbs"],
        ordinals: ["ordinals"],
        rocketpool: ["rocket-pool"],
        scroll: ["scroll"],
        shefi: ["shefi"],
        sia: ["siacoin"],
        solana: ["solana"],
        starknet: ["starknet"],
        thegraph: ["the-graph"],
        trading: ["market", "trading-video", "economic-calendar"],
        verasity: ["verasity", "verasity-source"],
        vitalikbuterin: ["vitalik-buterin"],
        wax: ["wax"],
        zcash: [
            "zcash-newsletter",
            "electric-coin",
            "zcash",
            "the-ambassadors-reception",
            "the-zf-a-v-club",
            "zcash-brasil",
            "zechub",
        ],
        zksync: ["zksync", "zksync-era"],
    },
};

export default BOARDS_CONFIG;
