name: Basic Checks Dev

on:
    pull_request:
        types: ready_for_review
        branches: [dev]
env:
    ENVIRONMENT: test

jobs:
    basic-checks:
        if: ${{ !(contains(github.event.pull_request.title, '(skip-ci)')) }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - uses: actions/setup-node@v3
              with:
                  node-version: "22.12.0"
                  cache: "yarn"
                  cache-dependency-path: |
                      yarn.lock
            - name: "Log current branch info"
              run: |
                  echo "On branch $( git rev-parse --abbrev-ref HEAD )"
                  echo "On commit $( git rev-parse --short HEAD )"
            - name: "Check node env"
              run: |
                  echo "node version $( node --version )"
                  echo "yarn version $( yarn --version )"
            - run: yarn --ignore-engines
            - run: yarn typecheck
            - run: yarn lint
