name: Deploy to zettaday (dev)

on:
    # # deploy runs when merging on dev
    # pull_request:
    #     types:
    #         - closed
    #     branches:
    #         - dev
    # and can be triggered manually also
    workflow_dispatch:

env:
    ENVIRONMENT: dev

    REACT_APP_LOGLEVEL: 0
    REACT_APP_API_BASE_URL: https://api.zettaday.com/
    REACT_APP_X_APP_ID: sBnL0RkWkM
    REACT_APP_X_APP_SECRET: 21gPAwU3uOUisMJJFJjaotbDxCmvCHKMh76Xlvb8XK2RkkvZHhtSfcUfoz6QiFx8zhZf31vxvKAFD7pkdmbjHiKwoVuS2iDOLjvC

    REACT_APP_ZAPPER_BASE_URL: https://api.zapper.fi/v1/
    REACT_APP_ZAPPER_BASE_URL_V2: https://api.zapper.fi/v2/
    REACT_APP_COINGECKO_BASE_URL: https://api.coingecko.com/api/v3/
    REACT_APP_DEFIPULSE_BASE_URL: https://data-api.defipulse.com/api/v1/
    REACT_APP_ETHERSCAN_BASE_URL: https://api.etherscan.io/api
    REACT_APP_ULTRA_SOUND_MONEY_BASE_URL: https://api.ultrasound.money/

    REACT_APP_SWAP_FEE: 10
    REACT_APP_SWAP_FEE_ADDRESS: "0xeb2eCdDF7db14D4Ebca0848F2a879162eb8A43F1"

    REACT_APP_GA_MEASUREMENT_ID: ""

    REACT_APP_FIRE_PROJECT_ID: gammaday-staging
    REACT_APP_FIRE_MEASUREMENT_ID: G-J6KTFT40XV

    REACT_APP_ALPHADAY_IPFS_GATEWAY: https://alphaday.infura-ipfs.io/ipfs/

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ !(contains(github.event.pull_request.title, '(skip-ci)')) && (github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true) }} # run only if triggered manually or via merged pr
        steps:
            - uses: actions/checkout@v2

            - name: Set tag ENV
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

            - uses: actions/setup-node@v3
              with:
                  node-version: "16.10.0"
                  cache: "yarn"
                  cache-dependency-path: |
                      yarn.lock

            - uses: volta-cli/action@v4

            - name: yarn install
              run: yarn

            - name: build
              run: yarn build:deploy
              env:
                  REACT_APP_ENVIRONMENT: ${{ env.ENVIRONMENT }}

                  REACT_APP_DEFIPULSE_API_KEY: ${{ secrets.STAGING__FRONTEND__API_KEY_DEFIPULSE }}
                  REACT_APP_ETHERSCAN_API_KEY: ${{ secrets.STAGING__FRONTEND__API_KEY_ETHERSCAN }}
                  REACT_APP_ETHPLORER_API_KEY: ${{ secrets.STAGING__FRONTEND__API_KEY_ETHPLORER }}
                  REACT_APP_ZAPPER_API_KEY: ${{ secrets.STAGING__FRONTEND__API_KEY_ZAPPER }}

                  REACT_APP_WALLET_CONNECT_PROJECT_ID: ${{ secrets.DEV__REACT_APP_WALLET_CONNECT_PROJECT_ID }}

                  REACT_APP_FIRE_API_KEY: ${{ secrets.DEV__REACT_APP_FIRE_API_KEY }}
                  REACT_APP_FIRE_AUTH_DOMAIN: ${{ secrets.DEV__REACT_APP_FIRE_AUTH_DOMAIN }}
                  REACT_APP_FIRE_STORAGE_BUCKET: ${{ secrets.DEV__REACT_APP_FIRE_STORAGE_BUCKET }}
                  REACT_APP_FIRE_MESSAGE_SENDER_ID: ${{ secrets.DEV__REACT_APP_FIRE_MESSAGE_SENDER_ID }}
                  REACT_APP_FIRE_APP_ID: ${{ secrets.DEV__REACT_APP_FIRE_APP_ID }}

                  AWS_REGION: "eu-west-1" # optional: defaults to us-east-1
                  SOURCE_DIR: "packages/main/build"

                  NODE_OPTIONS: "--max_old_space_size=4096"

            # deploy: sync to s3 and invalidate cloudfront cache
            - name: deploy
              uses: kefranabg/s3-sync-action@master # https://github.com/kefranabg/s3-sync-action
              with:
                  args: --acl public-read --follow-symlinks
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER__AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER__SECRET_ACCESS_KEY }}

                  AWS_S3_BUCKET: ${{ secrets.DEV__FRONTENDV2__S3_BUCKET }}
                  AWS_REGION: "eu-west-1" # optional: defaults to us-east-1
                  SOURCE_DIR: "packages/main/build"

    # Get message VARs and Notify team through discord of deployment
    notify:
        name: Notify
        runs-on: ubuntu-latest
        needs: deploy
        if: needs.deploy.result == 'success'

        steps:
            - uses: actions/checkout@v2.2.0
              with:
                  fetch-depth: 0

            - name: Get Repo Name
              run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

            - name: "Get Latest Tag"
              id: previoustag
              uses: "WyriHaximus/github-action-get-previous-tag@v1"

              # Notify Discord
            - name: Discord notification
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK__OPS_CHANNEL }}
              uses: "Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9"
              with:
                  args: "${{ env.REPOSITORY_NAME }}-${{ steps.previoustag.outputs.tag }} (${{ github.event.pull_request.title }}) has been deployed on ${{ env.ENVIRONMENT }}."
